<a href="https://colab.research.google.com/github/hemanshu16/ML_Labs/blob/main/ML_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import numpy as np
# import torch

In [ ]:

# # Input (temp, rainfall, humidity)
# inputs = np.array([[73, 67, 43],
# [91, 88, 64],
# [87, 134, 58],
# [102, 43, 37],
# [69, 96, 70]], dtype='float32')
# # Target (apples)
# targets = np.array([[56],
# [81],
# [119],
# [22],
# [103]], dtype='float32')
# print(targets[1])

[81.]


In [ ]:
# inputs = torch.tensor(inputs)
# targets = torch.tensor(targets)
# weights = torch.tensor(np.array([[0.5],[0.7],[0.5]], dtype='float32'))
# print(weights)

tensor([[0.5000],
        [0.7000],
        [0.5000]])


In [ ]:
# second  = torch.matmul(inputs,weights);
# biase = torch.tensor(np.array([[0.5],[0.5],[0.5],[0.5],[0.5]], dtype='float32'))
# print(second)
# print(biase + second)
# calculated  = biase+second

tensor([[104.9000],
        [139.1000],
        [166.3000],
        [ 99.6000],
        [136.7000]])
tensor([[105.4000],
        [139.6000],
        [166.8000],
        [100.1000],
        [137.2000]])


In [ ]:
# loss calculation 

# loss = targets - calculated;
# print(loss)
# loss_square  = loss.clone();
# for i  in range(5) :
#   loss_square[i][0] = loss_square[i][0]**2
# print(torch.sum(loss_square))


tensor([[-49.4000],
        [-58.6000],
        [-47.8000],
        [-78.1000],
        [-34.2000]])
tensor(15428.4082)


In [ ]:
# calculations 

nweights = [0,0,0]
newbiase = biase[0][0] - (0.2*0.5)*torch.sum(torch.mul(targets,0.5))
#print( inputs[  :  , 2 : 3])
for i in range(3) :
  nweights[i] = weights[i] - (0.2*0.5)*torch.sum(inputs[:,i:i+1]*loss)
  print((0.2*0.5)*torch.sum(inputs[:,i:i+1]*loss))
#weights = nweights


tensor(-2342.3398)
tensor(-2151.3298)
tensor(-1393.0699)


In [ ]:
import numpy as np
import torch

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')
# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

biase_size = 5
weights_size = 3 # features
m = 5
alpha = 0.01

inputs = torch.tensor(inputs)
targets = torch.tensor(targets)
weights = torch.tensor(np.full((weights_size, 1), 1, dtype='float32'))
print(weights)

biase = torch.tensor( np.full((biase_size, 1), 0.5, dtype='float32'))

for j in range(3) :
  print("\n\nno of count :- ",j,"\n")
  print(weights)
  print(biase)
  second  = torch.matmul(inputs,weights)
  calculated  = biase+second
  print(calculated)


  loss = calculated - targets;
  print(loss)
  loss_square  = loss.clone();
  for i  in range(m) :
    loss_square[i][0] = loss_square[i][0]**2
  print("MCE cost :-", torch.sum(loss_square))



  newbiase = biase[0][0] - (alpha*(1/m))*torch.sum(loss)
  
  print("Theta 0  :- ",newbiase)
  #print( inputs[  :  , 2 : 3])
  for i in range(weights_size) :
    weights[i] = weights[i] - (alpha*(1/m))*torch.sum(inputs[:,i:i+1]*loss)

  for i in range(biase_size) :
    biase[i][0] = newbiase
  print("New Values of Theta from 1 to ", weights_size, " :-\n" ,weights)

tensor([[1.],
        [1.],
        [1.]])


no of count :-  0 

tensor([[1.],
        [1.],
        [1.]])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]])
tensor([[183.5000],
        [243.5000],
        [279.5000],
        [182.5000],
        [235.5000]])
tensor([[127.5000],
        [162.5000],
        [160.5000],
        [160.5000],
        [132.5000]])
MCE cost :- tensor(111739.2500)
Theta 0  :-  tensor(-0.9870)
New Values of Theta from 1 to  3  :-
 tensor([[-126.1440],
        [-126.9420],
        [ -79.8100]])


no of count :-  1 

tensor([[-126.1440],
        [-126.9420],
        [ -79.8100]])
tensor([[-0.9870],
        [-0.9870],
        [-0.9870],
        [-0.9870],
        [-0.9870]])
tensor([[-21146.4434],
        [-27758.8262],
        [-32614.7246],
        [-21279.1523],
        [-26478.0566]])
tensor([[-21202.4434],
        [-27839.8262],
        [-32733.7246],
        [-21301.1523],
        [-26581.0566]])
MCE cost :- tensor(3.4

In [ ]:
#Example given In Lab

import numpy as np
import torch

# Input (temp, rainfall, humidity)
inputs = np.array([[20,24],
[21, 25],], dtype='float32')
# Target (apples)
targets = np.array([[40],
[50]], dtype='float32')

biase_size = 2
weights_size = 2 # features
m = 2
alpha = 0.5

inputs = torch.tensor(inputs)
targets = torch.tensor(targets)
weights = torch.tensor(np.full((weights_size, 1), 1, dtype='float32'))
print(weights)

biase = torch.tensor( np.full((biase_size, 1), 0.5, dtype='float32'))

for j in range(3) :
  print("\n\nno of count :- ",j,"\n")
  print(weights)
  print(biase)
  second  = torch.matmul(inputs,weights)
  calculated  = biase+second
  print(calculated)


  loss = calculated - targets;
  print(loss)
  loss_square  = loss.clone();
  for i  in range(m) :
    loss_square[i][0] = loss_square[i][0]**2
  print("MCE cost :-", torch.sum(loss_square))



  newbiase = biase[0][0] - (alpha*(1/m))*torch.sum(loss)
  print("Theta 0  :- ",newbiase)
  #print( inputs[  :  , 2 : 3])
  for i in range(weights_size) :
    weights[i] = weights[i] - (alpha*(1/m))*torch.sum(inputs[:,i:i+1]*loss)

  for i in range(biase_size) :
    biase[i][0] = newbiase
  print("New Values of Theta from 1 to ", weights_size, " :-\n" ,weights)

tensor([[1.],
        [1.]])


no of count :-  0 

tensor([[1.],
        [1.]])
tensor([[0.5000],
        [0.5000]])
tensor([[44.5000],
        [46.5000]])
tensor([[ 4.5000],
        [-3.5000]])
MCE cost :- tensor(32.5000)
Theta 0  :-  tensor(0.2500)
New Values of Theta from 1 to  2  :-
 tensor([[-3.1250],
        [-4.1250]])


no of count :-  1 

tensor([[-3.1250],
        [-4.1250]])
tensor([[0.2500],
        [0.2500]])
tensor([[-161.2500],
        [-168.5000]])
tensor([[-201.2500],
        [-218.5000]])
MCE cost :- tensor(88243.8125)
Theta 0  :-  tensor(105.1875)
New Values of Theta from 1 to  2  :-
 tensor([[2150.2500],
        [2569.0000]])


no of count :-  2 

tensor([[2150.2500],
        [2569.0000]])
tensor([[105.1875],
        [105.1875]])
tensor([[104766.1875],
        [109485.4375]])
tensor([[104726.1875],
        [109435.4375]])
MCE cost :- tensor(2.2944e+10)
Theta 0  :-  tensor(-53435.2188)
New Values of Theta from 1 to  2  :-
 tensor([[-1096016.7500],
        [-1309759.6